export const profilePicture = {
  'pikachu-2': require('../../img/pikachu-2.png'),
  'bullbasaur': require('../../img/bullbasaur.png'),
  'charmander': require('../../img/charmander.png'),
  'squirtle': require('../../img/squirtle.png'),
  'dratini': require('../../img/dratini.png'),
  'abra': require('../../img/abra.png'),
  'backpack': require('../../img/backpack.png'),
  'bellsprout': require('../../img/bellsprout.png'),
  'bracelet': require('../../img/bracelet.png'),
  'compass': require('../../img/compass.png'),
  'crown': require('../../img/crown.png'),
  'eevee': require('../../img/eevee.png'),
  'egg': require('../../img/egg.png'),
  'fist': require('../../img/fist.png'),
  'gear': require('../../img/gear.png'),
  'gotcha': require('../../img/gotcha.png'),
  'heart': require('../../img/heart.png'),
  'instinct-1': require('../../img/instinct-1.png'),
  'instinct': require('../../img/instinct.png'),
  'jigglypuff': require('../../img/jigglypuff.png'),
  'lucky-egg': require('../../img/lucky-egg.png'),
  'mankey': require('../../img/mankey.png'),
  'mega-ball': require('../../img/mega-ball.png'),
  'meowth': require('../../img/meowth.png'),
  'mew': require('../../img/mew.png'),
  'money-bag': require('../../img/money-bag.png'),
  'pidgey': require('../../img/pidgey.png'),
  'player-1': require('../../img/player-1.png'),
  'player': require('../../img/player.png'),
  'pokeball': require('../../img/pokeball.png'),
  'pokecoin': require('../../img/pokecoin.png'),
  'psyduck': require('../../img/psyduck.png'),
  'rattata': require('../../img/rattata.png'),
  'razz-berry': require('../../img/razz-berry.png'),
  'revive': require('../../img/revive.png'),
  'snorlax': require('../../img/snorlax.png'),
  'star-1': require('../../img/star-1.png'),
  'superball': require('../../img/superball.png'),
  'ultra-ball': require('../../img/ultra-ball.png'),
  'venonat': require('../../img/venonat.png'),
  'weedle': require('../../img/weedle.png'),
  'zubat': require('../../img/zubat.png'),
  'caterpie': require('../../img/caterpie.png'),
  'action-1': require('../../img/action-1.png'),
  'scene': require('../../img/scene.png'),
  // for mini icons on the map
  'pikachu-2_mini': require('../../img/mini_icon/pikachu-2_mini.png'),
  'bullbasaur_mini': require('../../img/mini_icon/bullbasaur_mini.png'),
  'charmander_mini': require('../../img/mini_icon/charmander_mini.png'),
  'squirtle_mini': require('../../img/mini_icon/squirtle_mini.png'),
  'dratini_mini': require('../../img/mini_icon/dratini_mini.png'),
  'abra_mini': require('../../img/mini_icon/abra_mini.png'),
  'backpack_mini': require('../../img/mini_icon/backpack_mini.png'),
  'bellsprout_mini': require('../../img/mini_icon/bellsprout_mini.png'),
  'bracelet_mini': require('../../img/mini_icon/bracelet_mini.png'),
  'compass_mini': require('../../img/mini_icon/compass_mini.png'),
  'crown_mini': require('../../img/mini_icon/crown_mini.png'),
  'eevee_mini': require('../../img/mini_icon/eevee_mini.png'),
  'egg_mini': require('../../img/mini_icon/egg_mini.png'),
  'fist_mini': require('../../img/mini_icon/fist_mini.png'),
  'gear_mini': require('../../img/mini_icon/gear_mini.png'),
  'gotcha_mini': require('../../img/mini_icon/gotcha_mini.png'),
  'heart_mini': require('../../img/mini_icon/heart_mini.png'),
  'instinct-1_mini': require('../../img/mini_icon/instinct-1_mini.png'),
  'instinct_mini': require('../../img/mini_icon/instinct_mini.png'),
  'jigglypuff_mini': require('../../img/mini_icon/jigglypuff_mini.png'),
  'lucky-egg_mini': require('../../img/mini_icon/lucky-egg_mini.png'),
  'mankey_mini': require('../../img/mini_icon/mankey_mini.png'),
  'mega-ball_mini': require('../../img/mini_icon/mega-ball_mini.png'),
  'meowth_mini': require('../../img/mini_icon/meowth_mini.png'),
  'mew_mini': require('../../img/mini_icon/mew_mini.png'),
  'money-bag_mini': require('../../img/mini_icon/money-bag_mini.png'),
  'pidgey_mini': require('../../img/mini_icon/pidgey_mini.png'),
  'player-1_mini': require('../../img/mini_icon/player-1_mini.png'),
  'player_mini': require('../../img/mini_icon/player_mini.png'),
  'pokeball_mini': require('../../img/mini_icon/pokeball_mini.png'),
  'pokecoin_mini': require('../../img/mini_icon/pokecoin_mini.png'),
  'psyduck_mini': require('../../img/mini_icon/psyduck_mini.png'),
  'rattata_mini': require('../../img/mini_icon/rattata_mini.png'),
  'razz-berry_mini': require('../../img/mini_icon/razz-berry_mini.png'),
  'revive_mini': require('../../img/mini_icon/revive_mini.png'),
  'snorlax_mini': require('../../img/mini_icon/snorlax_mini.png'),
  'star-1_mini': require('../../img/mini_icon/star-1_mini.png'),
  'superball_mini': require('../../img/mini_icon/superball_mini.png'),
  'ultra-ball_mini': require('../../img/mini_icon/ultra-ball_mini.png'),
  'venonat_mini': require('../../img/mini_icon/venonat_mini.png'),
  'weedle_mini': require('../../img/mini_icon/weedle_mini.png'),
  'zubat_mini': require('../../img/mini_icon/zubat_mini.png'),
  'caterpie_mini': require('../../img/mini_icon/caterpie_mini.png'),
  'action-1_mini': require('../../img/mini_icon/action-1_mini.png'),
  'scene_mini': require('../../img/mini_icon/scene_mini.png'),

//   'mystic-1 ': require('../../img/mystic-1.png'),
//   'mystic': require('../../img/mystic.png'),
//   'new': require('../../img/new.png'),
//   'open-pokeball': require('../../img/open-pokeball.png'),
//   'pawprints': require('../../img/pawprints.png'),
//   'lucky-eggs': require('../../img/lucky-eggs.png'),
//   'lure-module-1': require('../../img/lure-module-1.png'),
//   'lure-module-score': require('../../img/lure-module-score.png'),
//   'lure-module': require('../../img/lure-module.png'),
//   'lucky-egg-score': require('../../img/lucky-egg-score.png'),
//   'hyper-potion': require('../../img/hyper-potion.png'),
//   'incense-score': require('../../img/incense-score.png'),
//   'incense': require('../../img/incense.png'),
//   'incenses': require('../../img/incenses.png'),
//   'insignia-1': require('../../img/insignia-1.png'),
//   'insignia': require('../../img/insignia.png'),
//   'footprints': require('../../img/footprints.png'),
//   'fight': require('../../img/fight.png'),
//   'egg-1': require('../../img/egg-1.png'),
//   'egg-incubator-1': require('../../img/egg-incubator-1.png'),
//   'egg-incubator': require('../../img/egg-incubator.png'),
//   'camera': require('../../img/camera.png'),
//   'candy': require('../../img/candy.png'),
//   'clock': require('../../img/clock.png'),
//   'combat-power ': require('../../img/combat-power.png'),
//   'blue-team': require('../../img/blue-team.png'),
//   'battle': require('../../img/battle.png'),
//   'action':require('../../img/action.png'),
//   'augmented-reality-1': require('../../img/augmented-reality-1.png'),
//   'augmented-reality': require('../../img/augmented-reality.png'),
//   'map': require('../../img/map.png'),
//   'pikachu-1': require('../../img/pikachu-1.png'),
//   'pikachu': require('../../img/pikachu.png'),
//   'pointer': require('../../img/pointer.png'),
//   'pokebag': require('../../img/pokebag.png'),
//   'pokeballs': require('../../img/pokeballs.png'),
//   'pokecoins-1': require('../../img/pokecoins-1.png'),
//   'pokecoins': require('../../img/pokecoins.png'),
//   'pokedex': require('../../img/pokedex.png'),
//   'pokestop-1': require('../../img/pokestop-1.png'),
//   'pokestop-2': require('../../img/pokestop-2.png'),
//   'pokestop-3': require('../../img/pokestop-3.png'),
//   'pokestop': require('../../img/pokestop.png'),
//   'potion': require('../../img/potion.png'),
//   'red-team': require('../../img/red-team.png'),
//   'smartphone': require('../../img/smartphone.png'),
//   'star': require('../../img/star.png'),
//   'stardust': require('../../img/stardust.png'),
//   'super-potion': require('../../img/super-potion.png'),
//   'tornado': require('../../img/tornado.png'),
//   'tornado-1': require('../../img/tornado-1.png'),
//   'up-arrow': require('../../img/up-arrow.png'),
//   'valor-1': require('../../img/valor-1.png'),
//   'valor': require('../../img/valor.png'),
//   'yellow-team': require('../../img/yellow-team.png'),
};
