export const profilePicture = {
  'abra': require('../../img/abra.png'),
  // 'action-1': require('../../img/action-1.png'),
  // 'action':require('../../img/action.png'),
  // 'augmented-reality-1': require('../../img/augmented-reality-1.png'),
  // 'augmented-reality': require('../../img/augmented-reality.png'),
  // 'backpack': require('../../img/backpack.png'),
  // 'battle': require('../../img/battle.png'),
  'bellsprout': require('../../img/bellsprout.png'),
  // 'blue-team': require('../../img/blue-team.png'),
  // 'bracelet': require('../../img/bracelet.png'),
  // 'bullbasaur': require('../../img/bullbasaur.png'),
  // 'camera': require('../../img/camera.png'),
  // 'candy': require('../../img/candy.png'),
  'caterpie': require('../../img/caterpie.png'),
  'charmander': require('../../img/charmander.png'),
  // 'clock': require('../../img/clock.png'),
  // 'combat-power ': require('../../img/combat-power.png'),
  // 'compass': require('../../img/compass.png'),
  // 'crown': require('../../img/crown.png'),
  'dratini': require('../../img/dratini.png'),
  'eevee': require('../../img/eevee.png'),
  // 'egg-1': require('../../img/egg-1.png'),
  // 'egg-incubator-1': require('../../img/egg-incubator-1.png'),
  // 'egg-incubator': require('../../img/egg-incubator.png'),
  // 'egg': require('../../img/egg.png'),
  // 'fight': require('../../img/fight.png'),
  // 'fist': require('../../img/fist.png'),
  // 'footprints': require('../../img/footprints.png'),
  // 'gear': require('../../img/gear.png'),
  // 'gotcha': require('../../img/gotcha.png'),
  // 'heart': require('../../img/heart.png'),
  // 'hyper-potion': require('../../img/hyper-potion.png'),
  // 'incense-score': require('../../img/incense-score.png'),
  // 'incense': require('../../img/incense.png'),
  // 'incenses': require('../../img/incenses.png'),
  // 'insignia-1': require('../../img/insignia-1.png'),
  // 'insignia': require('../../img/insignia.png'),
  // 'instinct-1': require('../../img/instinct-1.png'),
  // 'instinct': require('../../img/instinct.png'),
  'jigglypuff': require('../../img/jigglypuff.png'),
  // 'lucky-egg-score': require('../../img/lucky-egg-score.png'),
  // 'lucky-egg': require('../../img/lucky-egg.png'),
  // 'lucky-eggs': require('../../img/lucky-eggs.png'),
  // 'lure-module-1': require('../../img/lure-module-1.png'),
  // 'lure-module-score': require('../../img/lure-module-score.png'),
  // 'lure-module': require('../../img/lure-module.png'),
  'mankey': require('../../img/mankey.png'),
  // 'map': require('../../img/map.png'),
  'mega-ball': require('../../img/mega-ball.png'),
  'meowth': require('../../img/meowth.png'),
  'mew': require('../../img/mew.png'),
  // 'money-bag': require('../../img/money-bag.png'),
  // 'mystic-1 ': require('../../img/mystic-1.png'),
  'mystic': require('../../img/mystic.png'),
  // 'new': require('../../img/new.png'),
  // 'open-pokeball': require('../../img/open-pokeball.png'),
  // 'pawprints': require('../../img/pawprints.png'),
  'pidgey': require('../../img/pidgey.png'),
  // 'pikachu-1': require('../../img/pikachu-1.png'),
  // 'pikachu-2': require('../../img/pikachu-2.png'),
  // 'pikachu': require('../../img/pikachu.png'),
  // 'player-1': require('../../img/player-1.png'),
  // 'player': require('../../img/player.png'),
  // 'pointer': require('../../img/pointer.png'),
  // 'pokebag': require('../../img/pokebag.png'),
  // 'pokeball': require('../../img/pokeball.png'),
  // 'pokeballs': require('../../img/pokeballs.png'),
  // 'pokecoin': require('../../img/pokecoin.png'),
  // 'pokecoins-1': require('../../img/pokecoins-1.png'),
  // 'pokecoins': require('../../img/pokecoins.png'),
  // 'pokedex': require('../../img/pokedex.png'),
  // 'pokestop-1': require('../../img/pokestop-1.png'),
  // 'pokestop-2': require('../../img/pokestop-2.png'),
  // 'pokestop-3': require('../../img/pokestop-3.png'),
  // 'pokestop': require('../../img/pokestop.png'),
  // 'potion': require('../../img/potion.png'),
  'psyduck': require('../../img/psyduck.png'),
  'rattata': require('../../img/rattata.png'),
  // 'razz-berry': require('../../img/razz-berry.png'),
  // 'red-team': require('../../img/red-team.png'),
  // 'revive': require('../../img/revive.png'),
  // 'scene': require('../../img/scene.png'),
  // 'smartphone': require('../../img/smartphone.png'),
  'snorlax': require('../../img/snorlax.png'),
  'squirtle': require('../../img/squirtle.png'),
  // 'star-1': require('../../img/star-1.png'),
  // 'star': require('../../img/star.png'),
  // 'stardust': require('../../img/stardust.png'),
  // 'super-potion': require('../../img/super-potion.png'),
  'superball': require('../../img/superball.png'),
  // 'tornado': require('../../img/tornado.png'),
  // 'tornado-1': require('../../img/tornado-1.png'),
  // 'ultra-ball': require('../../img/ultra-ball.png'),
  // 'up-arrow': require('../../img/up-arrow.png'),
  // 'valor-1': require('../../img/valor-1.png'),
  // 'valor': require('../../img/valor.png'),
  'venonat': require('../../img/venonat.png'),
  'weedle': require('../../img/weedle.png'),
  // 'yellow-team': require('../../img/yellow-team.png'),
  'zubat': require('../../img/zubat.png'),
};
